# Generated by Django 4.2.7 on 2025-12-04 18:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Category name must be at least 2 characters')])),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('color', models.CharField(default='#0d6efd', help_text='Category color in hex format (e.g., #0d6efd)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a task title (minimum 3 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Title must be at least 3 characters long')])),
                ('description', models.TextField(help_text='Enter a detailed description (minimum 10 characters)', validators=[django.core.validators.MinLengthValidator(10, 'Description must be at least 10 characters long')])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Select task priority', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='pending', help_text='Current status of the task', max_length=20)),
                ('due_date', models.DateField(help_text='Task due date')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours to complete the task', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of work')),
                ('hours_spent', models.DecimalField(decimal_places=2, help_text='Hours spent on this task', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'Hours must be at least 0.01'), django.core.validators.MaxValueValidator(Decimal('24.00'), 'Hours cannot exceed 24 per entry')])),
                ('description', models.TextField(blank=True, help_text='What work was done during this time', validators=[django.core.validators.MinLengthValidator(5, 'Description must be at least 5 characters')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(help_text='Task this time entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
